### ISSUE TITLE
criterion repo contains stack.yaml file for unboxed sums

### ISSUE THREAD

**Issue by RyanGlScott** [bos/criterion#117]
Specifically, [`stack-8.1.yaml`](https://github.com/bos/criterion/blob/fa9232a196f768336eead55b360c8c6b3c121f42/stack-8.1.yaml). It looks like it snuck through [here](https://github.com/bos/criterion/commit/349d50c731adf2dbfce795564d0351bc4a412be9).

Does this belong here?

**Comment by rrnewton** [comment]
Oops, no it shouldn't have got onto master.  Will fix.
