### ISSUE TITLE
Stop depending on deprecated hastache package

### ISSUE THREAD

**Issue by RyanGlScott** [bos/criterion#119]
The [`hastache`](http://hackage.haskell.org/package/hastache) package is listed as deprecated on Hackage. We should look into replacing it with a more maintained equivalent.

The `hastache` Haddocks recommend the [`mustache`](http://hackage.haskell.org/package/mustache) package. I've never tried it, though.

**Comment by RyanGlScott** [comment]
An issue: most of the actively maintained mustache template libraries on Hackage don't support GHC 7.4, which is the earliest version of GHC that we maintain support for in `criterion`:

* [`mustache-2.0.1`](http://hackage.haskell.org/package/mustache-2.0.1): GHC 7.8
* [`stache-0.1.6`](http://hackage.haskell.org/package/stache-0.1.6): GHC 7.8

**Comment by rrnewton** [comment]
Now that 8.0 is out, if the policy is three versions of GHC that should remove GHC 7.4 from the window.  @bos, is that the policy?

**Comment by bos** [comment]
You're welcome to nuke hastache support if it makes maintenance easier :-)

**Comment by RyanGlScott** [comment]
Well, one issue is that I don't know if `mustache` or `stache` (or some other mustache templating library) can be used as drop-in replacement for `hastache`. But even if they currently can't, I'm sure we could devise a way to make it work (even if it takes some PRs to accomplish it).

On a less technical level, I'm somewhat loathe to simply drop support for GHC 7.4. `criterion` is the _de factor_ benchmarking library, after all, and one thing that's sometimes useful to do is to compare the performance of programs between GHC versions, and if you can't build `criterion` with a particular GHC version, you'll have to benchmark it out-of-process, which has its own problems.

Again, this issue could possibly be overcome with a PR that relaxed the minimum GHC requirements for some mustache library of choice. I don't know how many bleeding-edge GHC features `mustache` or `stache` are using.

**Comment by rrnewton** [comment]
Actually, your argument applies doubly because from what you pasted earlier, @RyanGlScott, those alternative libs drop *7.6* support as well as 7.4.

Can we keep stumbling along with the deprecated hastache through the GHC 8.0 cycle and revisit this at 8.2?

**Comment by RyanGlScott** [comment]
Sure, I don't see a need to fix this immediately. `hastache` still works fine for `criterion`'s needs, and to be honest, I'm not 100% convinced that any of the possible replacements above are worth migrating to yet.

**Comment by RyanGlScott** [comment]
We have finally replaced `hastache` with `microstache`, a fork of `stache` with a smaller dependency footprint and wider GHC support. Se df4515c4ba62d444b803d1e80e0f8f96eb4a8d31.
