### ISSUE TITLE
Feedback on `criterion` in literature

### ISSUE THREAD

**Issue by Icelandjack** [bos/criterion#122]
A recent paper [Robust benchmarking in noisy environments](http://arxiv.org/pdf/1608.04295.pdf) has feedback on `criterion`

> While  it  is  impossible  to  eliminate  performance  variation entirely, benchmarking methodologies that attempt to account for both measurement error and external sources of variation do exist. For example, the Haskell microbenchmarking  package `criterion` attempts  to  thwart  error  due  to timer inaccuracy by growing the number of benchmark executions  per  timing  measurement  as  more  timing  measurements are  obtained.  After  all  measurements  are  taken,  a  summary estimate of the benchmark run time is obtained by examining the  derivative  of  the  ordinary  least  squares  regression  line at  the  point  of  a  single  evaluation  point.  There  are  three disadvantages  to  this  approach.  First,  the  least  squares  fit  is
sensitive to outliers (though `criterion` does warn the user if outliers are detected). Second, measurements made earlier in this experiment are highly vulnerable to timer error, since few benchmark repetitions are used. These early measurements can skew  the  regression,  and  hence  also  skew  the  final  run  time estimate.  Third,  measurements  made  later  in  the  experiment can  repeat  the  benchmark  more  times  than  are  necessary to  overcome  timer  error,  constituting  an  inefficient  use  of experiment time.

**Comment by bos** [comment]
That's a cool paper. Thanks for the link!
