### ISSUE TITLE
Tutorial: choice of KDE kernel width

### ISSUE THREAD

**Issue by ocramz** [bos/criterion#129]
The tutorial contains the following comment : " In order to get good information out of a histogram, you have to choose a suitable bin size. This is a fiddly manual task. In contrast, a KDE is likely to be informative immediately, with no configuration required." (source : http://www.serpentine.com/criterion/tutorial.html#understanding-charts )

This is incorrect, since any kernel estimate depends on the (arbitrary) choice of kernel width. 

Does `criterion` infer the kernel size from the data?

**Comment by bos** [comment]
Yes.

**Comment by ocramz** [comment]
And where in the sourcecode is this estimation made?
