### ISSUE TITLE
New maintainership

### ISSUE THREAD

**Issue by sjakobi** [bos/criterion#133]
Motivation:

* Important PRs like https://github.com/bos/criterion/pull/123 aren't getting finished and released.
* Issues and feature requests are not being addressed.

In sum criterion is currently stagnating and not seeing as much contribution activity as it could.

Proposal:

* Let's make a call for new maintainers on Haskell Cafe and r/haskell.
* Move criterion to a new GitHub organization "haskell-criterion" to simplify administration (["criterion"](https://github.com/criterion) is already in use).

Chris Done has done [something very similar](https://www.reddit.com/r/haskell/comments/5wpa9e/haskellcafe_looking_for_maintainers_or/) with his projects recently and as a result his [path](https://github.com/commercialhaskell/path), [intero](https://github.com/commercialhaskell/intero) and [hindent](https://github.com/commercialhaskell/hindent) projects are seeing a lot of new activity.

**Comment by RyanGlScott** [comment]
@bos recently made me a co-maintainer - I promise I'll try to keep up with pull requests as they come in.

Moreover, I've merged #123, which was the impetus for this ticket. I don't have the power to transfer this to another organization (nor do I think that's necessarily worth it), so I'll opt to close this.

**Comment by sjakobi** [comment]
Great news! Thanks a lot for taking on the task! :)
