### ISSUE TITLE
Benchmarking mutable IO operations

### ISSUE THREAD

**Issue by merijn** [bos/criterion#134]
In it's current form Criterion benchmarks that need an environment always share the environment over many runs of the same benchmark. This is fine for timing simple IO operations and pure functions, but makes it hard to benchmark mutable operations such a sorting a mutable Vector in place.

Ideally Criterion should have an interface to support benchmarks that allocate a fresh environment for every run of the algorithm.

**Comment by RyanGlScott** [comment]
Fixed in #136.
