### ISSUE TITLE
Benchmarking IO operations that grow the amount of live data.

### ISSUE THREAD

**Issue by merijn** [bos/criterion#135]
Criterion runs many batches of many repeats of the same benchmark to acquire timings. This is fine for pure functions, but when benchmarking IO operations that grow the heap this can lead to earlier runs impacting the timings of later runs. Since GHC's copying GC results in longer GC pauses the bigger the amount of live data.

For example: Suppose we want to benchmark writing to a `Chan`. Naively we can use `env` to allocate a `Chan` for our benchmark and benchmark `writeChan env ()` to time writing to the `Chan`. However, since the entire `Chan` remains live over many runs of this action we end up repeatedly growing it's contents, resulting in later runs being disproportionately affected by GC work from earlier runs. If criterion runs 1,000 batches of 1,000 repeats, the last batch has to GC 999,000 values in the `Chan` unrelated to that benchmark.

Ideally Criterion would allow benchmarks that share an environment only over 1 one "batch" of benchmarks, so that in our previous example we allocate one `Chan`, perform 1,000 writes, then GC it and allocate a fresh `Chan` for the next batch of 1,000 writes. This should perform more realistic timings.

**Comment by RyanGlScott** [comment]
Fixed in #136.
