### ISSUE TITLE
Document the usage of glob

### ISSUE THREAD

**Issue by capitanbatata** [bos/criterion#157]
I could not find any documentation of the use of glob patterns for selecting benchmarks. Luckily there was [a question](https://github.com/bos/criterion/issues/101) asked before that helped me. Is it possible to include this information somewhere?

Also including an example in the documentation of [`MatchType`](http://hackage.haskell.org/package/criterion-1.1.4.0/docs/Criterion-Main-Options.html#t:MatchType) might also help.

**Comment by RyanGlScott** [comment]
Sounds reasonable to me. Care to submit a PR? :)

**Comment by capitanbatata** [comment]
This is a low hanging fruit it seems, so no problem. I can expand the documentation in `MatchType`, and I don't know whether I could add comments in some of the examples (e.g. `Fibber`) to mention this. Can you think of other or more appropriate places?

**Comment by RyanGlScott** [comment]
Updating the `Glob` constructor's Haddocks would be a great thing. Aside from that, I think the other part of the codebase that would be worth updating is the discussion of `--match glob` in [the tutorial](https://github.com/bos/criterion/blob/2631f33966e46958cfac03adcafbc83321ca03eb/www/tutorial.md#specifying-benchmarks-to-run).

I don't see any point in updating the examples, since they don't directly pertain to `--match glob`'s functionality itself.

**Comment by capitanbatata** [comment]
Indeed, I didn't see that the tutorial is part of the repository. Nice :) I'll update the haddock and the tutorial then.

**Comment by capitanbatata** [comment]
A PR is on its way. As an aside, I could not build criterion with stack:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for criterion-1.2.2.0:
    microstache-1 must match >=1.0.1 && <1.1 (latest applicable is 1.0.1.1)
needed since criterion-1.2.2.0 is a build target.
```

Running `stack solver` gives:

```
* Dependencies to be added
    extra-deps:
    - aeson-1.2.2.0
    - base-compat-0.9.3
    - criterion-1.2.2.0
    - integer-logarithms-1.0.2
    - microstache-1.0.1.1
    - primitive-0.6.2.0
    - scientific-0.3.5.2
    - th-abstraction-0.2.6.0
    - vector-0.12.0.1
    - vector-binary-instances-0.2.3.5

* Dependencies to be deleted
    extra-deps:
    - microstache-1
```

But I guess just adding `    - microstache-1.0.1.1` should be enough. Should I also update the `stack.yaml` in this case?

**Comment by RyanGlScott** [comment]
> But I guess just adding `    - microstache-1.0.1.1` should be enough. Should I also update the `stack.yaml` in this case?

Sure.
