### ISSUE TITLE
Typo in JSON output?

### ISSUE THREAD

**Issue by capitanbatata** [bos/criterion#167]
The JSON reports reads:

```json
[
  "criterio",
  "1.2.3.0",
  [...
```

Was this intentional?

**Comment by RyanGlScott** [comment]
Oops, that does indeed look like a typo. I'll make sure to fix this in the next major release of `criterion`.

**Comment by RyanGlScott** [comment]
Addressed in commit ac2a230a0cdf2fb112334324c0e872775593f04e.
