### ISSUE TITLE
Remove depracted functions relying on GCStats

### ISSUE THREAD

**Issue by AndreasPK** [bos/criterion#171]
GHC Head is already making changes expected to land in 8.4 such as removing GCStats.

Criterion still has (deprecated) functions depending on these.
Removing these would make it easier to build criterion with GHC Head moving foward.

Just removing them seems easiest. 
It might be a bit early for this, however it seems the old Interface is already [broken](https://ghc.haskell.org/trac/ghc/ticket/14516) in GHC-8.2.

**Comment by RyanGlScott** [comment]
My plan is to rip them out for good once the first 8.4 release candidate lands, at which point I'll release a new major version of `criterion`. Until then, I'll leave this ticket open as a reminder.

**Comment by RyanGlScott** [comment]
Addressed in commit ac2a230a0cdf2fb112334324c0e872775593f04e.
