### ISSUE TITLE
`perRunEnv` yields too small result?

### ISSUE THREAD

**Issue by as-capabl** [bos/criterion#174]
I wrote a benchmark using `perRunEnv` and got too small result.

Here's an example:

```haskell
module Main where
import Criterion.Main
import Control.Concurrent

main =
  do
    defaultMain
      [
        bench "whnfIO" $ whnfIO $ threadDelay 100000,
        bench "perRunEnv" $ perRunEnv (return ()) $ \_ -> threadDelay 100000
      ]
```

I run above code in linux environment and got:

```
benchmarking whnfIO
time                 100.3 ms   (100.2 ms .. 100.4 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 100.2 ms   (100.2 ms .. 100.3 ms)
std dev              78.44 μs   (63.88 μs .. 97.07 μs)

benchmarking perRunEnv
time                 19.46 ms   (14.38 ms .. 33.42 ms)
                     0.969 R²   (0.967 R² .. 1.000 R²)
mean                 36.17 ms   (25.07 ms .. 44.49 ms)
std dev              12.71 ms   (0.0 s .. 14.41 ms)
variance introduced by outliers: 73% (severely inflated)
```

I expect that `perRunEnv` should return a result near 100 ms like `whnfIO`.

**Comment by RyanGlScott** [comment]
Indeed, I can reproduce this issue.

@merijn, do you know what is going on here? In particular, I just noticed these lines (within `runBenchmarkable`), which smell a bit strange to me:

https://github.com/bos/criterion/blob/32bf84f703c9abd9e65d5b12440f7ec733c22516/Criterion/Measurement.hs#L251-L262

In particular, note that `count` is hard-coded to `1` if running `perRunEnv`! If I'm reading that correctly... doesn't that mean we'll only run the function a single time?

**Comment by merijn** [comment]
@RyanGlScott Note that the perRun case handles the count/recursion on line 245 (i.e. outside of the environment allocation/cleanup that work does). And I got reasonable results in my own stuff before this ever got merged.

I have some sneaking suspicions what might be happening, but I'll have to look into it.

**Comment by merijn** [comment]
Ok, I have found the issue and it's the dumbest possible issue you can think off... 

https://github.com/bos/criterion/blob/32bf84f703c9abd9e65d5b12440f7ec733c22516/Criterion/Measurement.hs#L201-L227

Note how line 205 sets `measIters` to `iters`, while the `perRunEnv` setup will really only be timing a single run, then adding the measurements for each in the end. However, line 218 happily adds these iter counts, which means that an `n` iteration benchmark using `perRunEnv` will happily compute statistics for `n * n` runs based on the measurement of `n` iterations, completely bollocksing up the end results for obvious reasons.

A quick hack workaround gives me, perfectly reasonable seeming, result of:
```
benchmarking perRunEnv
time                 105.7 ms   (97.59 ms .. 110.0 ms)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 108.0 ms   (106.2 ms .. 108.9 ms)
std dev              1.543 ms   (0.0 s .. 1.661 ms)
variance introduced by outliers: 19% (moderately inflated)
```

I'll fix it in a "proper" way and submit a PR for that sometime in the next couple of days.

**Comment by as-capabl** [comment]
@RyanGlScott @merijn 
Great work! Thanks!
