### ISSUE TITLE
Final measurement is dropped

### ISSUE THREAD

**Issue by patrickdoc** [bos/criterion#179]
I've been digging deeper into some of the internals for performance reasons, and I noticed something a little strange in the core loop.

https://github.com/bos/criterion/blob/52ef4a7699237a8952475146c51fc5d8ebff5876/Criterion/Measurement.hs#L273-L292

If you look at line 290, you'll see that the returned vector does not contain the current measurement `m`. `m` *is* used to increment the `overThresh` end condition, however. So it seems as if a perfectly good measurement is lost.

I've looked through the blame history regarding that line, and I didn't find any explanation or changes. So either this has just slipped under the radar, or I am completely missing something (certainly possible).

(Also, a heads up: I have a couple issues/suggestions for this loop. Unfortunately, it is the real root of #160, #161, and #162, which means #178 may have been a mistake ☹️  But that is a discussion for another issue)

**Comment by RyanGlScott** [comment]
> (Also, a heads up: I have a couple issues/suggestions for this loop. Unfortunately, it is the real root of #160, #161, and #162, which means #178 may have been a mistake frowning_face But that is a discussion for another issue)

Interesting. In that case, I'm glad I didn't rush to put out a new release after that change. I'm curious to see what comes of your investigation.

(Also, an enormous thank-you for digging so deep into the `criterion` codebase to fix these sorts of issues!)

**Comment by patrickdoc** [comment]
@RyanGlScott, with the merging of #187, most of my issues are now basically swept under the rug.
The performance is now good enough that the slight problems with the loop conditions above just go away.

For example, the `overThresh` condition checks that we have at least 300 ms of measured time. Benchmarks now consistently generate more than 4s of data.

The `Sample is empty` errors are also solved because benchmarks regularly generate 30-40 samples above the threshold.

At this point, there are two options. 1) Make slight cleaning changes to the loop, like removing the `overThresh` check and adding in the missing last benchmark. 2) Leave it as is because there is nothing "wrong" about it per se. It just is somewhat redundant.

**Comment by RyanGlScott** [comment]
OK. If you feel that it's fine in its current state, I'd be alright with leaving it alone. We could perhaps revisit this decision if it proves to be troublesome in the future.
