### ISSUE TITLE
`pureFunc` does unnecessary allocation

### ISSUE THREAD

**Issue by patrickdoc** [bos/criterion#183]
`pureFunc`, and thereby `whnf` and `nf`, is currently allocating memory it shouldn't be.

https://github.com/bos/criterion/blob/f782086c79f753b249018b3b34e31dc142b9de4d/Criterion/Types.hs#L316-L333

Following the discussion and techniques in [this reddit thread](https://www.reddit.com/r/haskell/comments/7u3xxw/evaluate_vs_seq_and_garbage_collection/?st=jd5enuv2&sh=a3a9e947), and in particular [this comment](https://www.reddit.com/r/haskell/comments/7u3xxw/evaluate_vs_seq_and_garbage_collection/dtil5ke/?st=jd5dt60n&sh=95733903), we can see that currently a thunk is allocated for values that will never be used.

Here's a demonstration

    module Main where
    import Criterion.Main

    main :: IO ()
    main = defaultMain
      [ bench "fast" $ whnf id [(1 :: Int)..100000] ]

    -----------------------------------------------------------

    benchmarking fast
    time                 9.024 ns   (8.954 ns .. 9.100 ns)
                         1.000 R²   (0.999 R² .. 1.000 R²)
    mean                 8.996 ns   (8.951 ns .. 9.060 ns)
    std dev              181.4 ps   (137.9 ps .. 246.4 ps)
    variance introduced by outliers: 31% (moderately inflated)

    17,616,724,272 bytes allocated in the heap
        52,372,744 bytes copied during GC
           720,256 bytes maximum residency (1239 sample(s))
            61,680 bytes maximum slop
                 6 MB total memory in use (0 MB lost due to fragmentation)

If we modify the `otherwise` case in `pureFunc`, we can create a version that does not allocate extra (at least on my computer using 8.2.1).

    | otherwise = let !y = reduce (f x)
                  in evaluate y >> go f x (n-1)

Which produces

    benchmarking fast
    time                 6.010 ns   (5.923 ns .. 6.129 ns)
                         0.998 R²   (0.997 R² .. 0.999 R²)
    mean                 6.129 ns   (6.041 ns .. 6.238 ns)
    std dev              331.1 ps   (278.9 ps .. 377.7 ps)
    variance introduced by outliers: 77% (severely inflated)

    92,983,968 bytes allocated in the heap
    54,215,432 bytes copied during GC
       714,472 bytes maximum residency (1271 sample(s))
        60,192 bytes maximum slop
             6 MB total memory in use (0 MB lost due to fragmentation)

The allocation savings are quite something (and garbage collection is the next issue after this :P). More importantly though, we have removed 3 ns of overhead from the core loop.

Unfortunately, this function is quite volatile; the smallest source change drastically changes its performance. Finding the correct implementation is difficult. As I see it, it has to conform to the following rules:

- [ ] Apply `f` to `x` on every iteration
- [ ] Do not allocate the result of `f x`
- [ ] Eliminate the `id` from `whnf`
- [ ] *Possibly inline `rnf` in `nf`
- [ ] Maintain all of these regardless of optimization from the user

From a few small tests, it would seem the current implementation is only failing on the allocation front.

I've written 3 or 4 versions that all *seem* to work, but I'm not really sure how to choose one with any sort of confidence.

**Comment by RyanGlScott** [comment]
I'll add one more item to that checklist:

* [ ] Should not be broken by `-fstatic-argument-transformation`

I write "should" and not "must" since `criterion` doesn't actually conform to this rule at the moment (https://github.com/bos/criterion/issues/138). So if you find a solution that doesn't check off this item, don't worry too much about it.
