### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by Fuuzetsu** [bos/criterion#188]
Hello!

I just hit a bug that was fixed two months ago (#162). I'm on 1.3.0.0. Is there anything holding up a release? Could I help somehow to get it out perhaps?

**Comment by RyanGlScott** [comment]
Sounds good to me.

@patrickdoc, is there anything else you'd like to get merged before another release?

**Comment by patrickdoc** [comment]
Nope, I think I'm done with code changes barring any new bugs.

**Comment by RyanGlScott** [comment]
I've uploaded [`criterion-1.4.0.0`](https://hackage.haskell.org/package/criterion-1.4.0.0) to Hackage.
