### ISSUE TITLE
Split out criterion-core ?

### ISSUE THREAD

**Issue by ocramz** [bos/criterion#189]
I would like a minimalistic performance library, that doesn't depend on HTML or javascript libraries (namely, `microstache`, `js-*`), or require processing of command line arguments (i.e. `optparse-applicative`). The main `criterion` library would then import `criterion-core` and re-add the bells and whistles.

Additionally, other profiling libraries could just import `criterion-core`, without incurring a large transitive dependency cost. The burden of run-time analysis and presentation would be transferred to these consumer libraries.

I'm willing to re-arrange the codebase in this fashion, would you accept such a PR? 
Thank you

**Comment by RyanGlScott** [comment]
While I can appreciate the desire to minimize dependencies, I'm not sure how far you're going to get by just removing the HTML and CLI argument-parsing bits. Here's the dependency graph for `criterion`:

![deps](https://user-images.githubusercontent.com/2364661/37556165-5d469446-29c8-11e8-853c-a987d048f522.png)

The bulk of `criterion`'s dependencies come from `statistics`, which is actually used in the "core" of `criterion`.

Moreover, I'm not sure how feasible this idea even is. Most consumers use `criterion` by way of `defaultMain`, which is intended to be used for producing a full executable. By necessity, that must include the "bells and whistles". Or am I missing something?

**Comment by RyanGlScott** [comment]
> @RyanGlScott Thank you for the clarifications and the graph, which is very enlightening. (BTW what did you use to produce it?)

I used [`cabal-plan`](http://hackage.haskell.org/package/cabal-plan):

```
$ cabal get criterion-1.4.0.0                                         
$ cd criterion-1.4.0.0/                                                                                                    
$ echo "packages: ." > cabal.project
$ cabal new-build --disable-tests --disable-benchmarks
$ cabal-plan --builddir=dist-newstyle --hide-builtin dot --tred --tred-weights | dot -Tpng -odeps.png
```

> In this picture, `criterion-core` could get rid of `statistics` as well, and only provide combinators for raw timing measurements on single functions (i.e. `Criterion.Measurement` and its direct dependencies).

`Criterion.Measurement` has `statistics` as a direct dependency, actually, since it imports `Criterion.Types` (which in turns uses `statistics`).

> I think It's not inconceivable that some consumer libraries might want to plug in alternative statistical functionality, or use the raw data in novel ways.

Perhaps. But I'm still unclear as to why exactly you want to go through this trouble in the first place. What exactly _is_ your use case? Why doesn't `criterion` suffice? (I find "dependencies" to be a not very compelling argument, since each one is accomplishing something important!)

**Comment by ocramz** [comment]
One of my aims with this is to provide `criterion-core` as a component in a modular benchmarking library which would allow direct comparison of timing functions and statistical regression methods, in the interest of scientific rigor and reproducibility.

I do understand that a new, derivative library would add some burden on the shoulders of the group of maintainers, so I'm willing to pursue this project independently via a fork of criterion, if this split doesn't align with the goals of the library. Obviously the fork will give all due credit to the original authors.

**Comment by RyanGlScott** [comment]
OK, things are starting to make more sense now. If you're keen on pursuing this, whip up a PR and I'll make a call on whether I like it enough to merge :)

One minor thing: I'm not particularly fond of the `-core` suffix. Is your intention to just partition off the measurement-related aspects of `criterion`? If so, I think I'd favor the name `criterion-measurement`, or something akin to that.

**Comment by larskuhtz** [comment]
Are you aware of [https://github.com/vincenthz/hs-gauge]?

**Comment by ocramz** [comment]
@larskuhtz No, I didn't, thank you!

**Comment by larskuhtz** [comment]
@ocramz I think a llight-weight "core" benchmark library would be really useful. By supporting different frontends, it would allow to join forces on the basics (and avoid forks). 

For instance, In automated test and CI builds, visual output isn't required and those scenarios would benefit from a simpler front-end package. Also it seems overkill to depend on the full statistics package just for computing OLS regressions.

**Comment by ocramz** [comment]
@larskuhtz thank you for your feedback, I absolutely agree. I see hs-gauge has still some accuracy issues, whereas criterion seems to be more reliable and most importantly works on the three major OS ; I will start working on this "separation of concerns" PR within the next days. Please feel free to check back and give feedback, suggestions, etc.

**Comment by ocramz** [comment]
@RyanGlScott @larskuhtz the PR I had in mind materialized : #191 . I look forward to your feedback!

**Comment by RyanGlScott** [comment]
Implemented in https://github.com/bos/criterion/pull/191.
