### ISSUE TITLE
add CONTRIBUTORS file

### ISSUE THREAD

**Issue by ocramz** [bos/criterion#190]
Contributors, current maintainers should be mentioned

**Comment by RyanGlScott** [comment]
I'll be honest—I'm not a fan of CONTRIBUTORS files in general. In most cases, they simply add another hoop to jump through for new contributors, and don't really tell you much that the commit history doesn't already show.

The maintainer field of `criterion.cabal` is indeed out of date, though. I'll update that.

**Comment by RyanGlScott** [comment]
The second part of https://github.com/bos/criterion/issues/190#issuecomment-376524965 was done in https://github.com/bos/criterion/commit/ca0bc30a5917356b3f790b19d3b8b2c662c104a9.
