### ISSUE TITLE
Base-compat 0.10.0.0 breaks build

### ISSUE THREAD

**Issue by kcsongor** [bos/criterion#192]
The `<>` operator is now exported by `base-compat-0.10.0.0`, so `criterion` doesn't build

```
Criterion/Report.hs:196:37: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Data.Monoid.<>’,
                             imported from ‘Data.Monoid’ at Criterion/Report.hs:43:21-24
                          or ‘Prelude.Compat.<>’,
                             imported from ‘Prelude.Compat’ at Criterion/Report.hs:54:1-21
                             (and originally defined in ‘Data.Semigroup’)
    |
196 |             Object y' -> Object (x' <> y')
    |                                     ^^
```

**Comment by RyanGlScott** [comment]
I've restricted the upper version bounds on `base-compat` to < 0.10 for now.

**Comment by kcsongor** [comment]
Thanks, the revision did the trick!

**Comment by RyanGlScott** [comment]
Ideally, I'd like to swap out `base-compat` for `base-compat-batteries` in `criterion` so that I can make use of its `Prelude` that reexports `Semigroup((<>))`. But that will first require a new release of `aeson` which supports `base-compat-0.10`, so there's not much I can do on this front for now.

**Comment by kcsongor** [comment]
Fair enough, I'm happy with this workaround for the time being.

**Comment by RyanGlScott** [comment]
I've uploaded [`criterion-1.4.1.0`](http://hackage.haskell.org/package/criterion-1.4.1.0) to Hackage, which uses `base-compat-batteries-0.10` (and thus supports `base-compat-0.10`).
