### ISSUE TITLE
Printing during benchmark operation

### ISSUE THREAD

**Issue by nobrakal** [bos/criterion#194]
I am interesting in developing a tool to benchmark graph libraries and I find the output of `runAndAnalyseOne` very verbose (in fact it is `analyseOne` who is prolix).

As I can't find anything that return me a `DataRecord` without printing anything, for now, I am re-defining `analyseOne` to print anything during benchmark, and use the result to print what I want.

I think it can be a good idea to separate real operations from printing ones, maybe by sequencing them or if the two are too intertwined, by providing two functions.

What do you think ?

**Comment by RyanGlScott** [comment]
Hi @nobrakal. Have you tried running `analyseOne` with a [`Verbosity`](https://github.com/bos/criterion/blob/3f130ccc23e77136a22491d8de5b480e5b3aecfc/Criterion/Types.hs#L95) of `Quiet` in the `Config` you pass to `runCriterion`? I believe that should silence the benchmarking output.

**Comment by nobrakal** [comment]
Oh, you are right, I didn't thought this parameter can be hidden here.

Sorry of the inconvenience, and thank you :)
