### ISSUE TITLE
JavaScript syntax error in HTML output if benchmark name contains '

### ISSUE THREAD

**Issue by sshine** [bos/criterion#204]
If the first argument to [`bench`](https://hackage.haskell.org/package/criterion-1.5.2.0/docs/Criterion.html#v:bench) (the name of the benchmark) contains a `'`, the HTML output fails.

A part of the generated output looks like:

    var ylabels = [[-0,'<a href="#b0">collatz/collatz</a>'],[-1,'<a href="#b1">collatz/collatz2</a>'],[-2,'<a href="#b2">collatz/collatz'</a>'],[-3,'<a href="#b3">collatz/collatz''</a>'],];

The syntax error is caused by this part:

    [-2,'<a href="#b2">collatz/collatz'</a>']

Since the name is injected into JavaScript code, it should be properly escaped.

An [ES5 single-quote literal](https://es5.github.io/#x7.8.4) is described as:

> SourceCharacter but not single-quote ' or backslash \ or LineTerminator
> \ EscapeSequence
> LineContinuation

**Comment by RyanGlScott** [comment]
What version of `criterion` are you using? This should be fixed as of `criterion-1.5.2.0`, which incorporates a fix for #202 (which I believe this issue isa duplicate of).

**Comment by sshine** [comment]
I'm using `criterion-1.4.1.0`, so that should explain it.

I'll close this issue and upgrade. :-)
