### ISSUE TITLE
Legend boxes can hide data points in HTML file

### ISSUE THREAD

**Issue by nh2** [bos/criterion#207]
This can be quite confusing; pictures below:

**Comment by roman** [comment]
<img width="530" alt="screenshot 2018-12-18 11 46 17" src="https://user-images.githubusercontent.com/7335/50178996-ce4f8000-02ba-11e9-811c-08a6729c49ad.png">
<img width="523" alt="screenshot 2018-12-18 11 46 38" src="https://user-images.githubusercontent.com/7335/50178997-ce4f8000-02ba-11e9-88b5-c26c49a38018.png">

**Comment by nh2** [comment]
There is already some transparency on the white `<div>` but depending on the screen it is _extremely_ hard to see.

We should either increase the transparency, or move the legend outside of the plot (e.g. further up).

**Comment by Lythenas** [comment]
I'm also having this Problem with the overview chart when using long names. Which basically makes the chart unreadable.

![image](https://user-images.githubusercontent.com/32217236/63586605-f574f480-c5a1-11e9-90c6-ed284fad2163.png)

Also the legend can be bigger than the actual graph.

![image](https://user-images.githubusercontent.com/32217236/63586643-15a4b380-c5a2-11e9-9ed3-875b60a773a3.png)

I think moving the legend above the plot would be fine. Except maybe for the overview chart. There is also more than enough space on the left and right to move the legend there. But that probably depends on screen resolution.

Maybe something like transparency (or even completely invisible) on hover would also work.

**Comment by RyanGlScott** [comment]
#229 changes the way legends work:

* Legends are no longer displayed over the time-per-iteration charts, as they don't really convey much useful information beyond what is already present in the titles. This should resolve the issue in https://github.com/bos/criterion/issues/207#issuecomment-448346753.
* By default, legends are no longer displayed on top of the overview chart, which should fix https://github.com/bos/criterion/issues/207#issuecomment-524266321. The legend can be toggled, however, and if it is enabled, it is no longer rendered on top of the bars themselves.

As a result, I'm deeming this issue fixed. Please re-open if you disagree.
