### ISSUE TITLE
" in json output is html escaped

### ISSUE THREAD

**Issue by reactormonk** [bos/criterion#219]
When running criterion with `--template json --output mydata.json`, the json output contains html escapes.

```
[{&quot;reportAnalysis&quot;:{&quot;anMean&quot;:{&quot;estError&quot;:{&quot;confIntLDX&quot;
```
Stack lts 13.26

**Comment by RyanGlScott** [comment]
Good catch. For some bizarre reason, `json.tpl` is using `{{json}}`, which causes the contents of `json` to be HTML-escaped. I think we actually want `{{{json}}}`, which avoids the escaping.

Patch incoming.

**Comment by RyanGlScott** [comment]
With #220, the output of `--template json` is:

```
[{"reportAnalysis":{"anMean":{"estError":{"confIntLDX":...
```

Is this to your liking, @reactormonk?

**Comment by reactormonk** [comment]
:+1:

**Comment by RyanGlScott** [comment]
I've uploaded [`criterion-1.5.6.2`](http://hackage.haskell.org/package/criterion-1.5.6.2) to Hackage with these changes.
