### ISSUE TITLE
benchmark statistics are non-sense with mwc-random-0.15.0.0

### ISSUE THREAD

**Issue by phadej** [bos/criterion#228]
An example from https://github.com/sweirich/lennart-lambda run by

```
cabal run -w ghc-8.8.3 LC --constraint='mwc-random <0.15' -- --match prefix "nf/Scoped"
```

(Note the constraint), the results look normal:

```
benchmarking nf/Scoped/
time                 10.36 ms   (10.22 ms .. 10.51 ms)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 10.18 ms   (10.15 ms .. 10.24 ms)
std dev              131.5 μs   (76.42 μs .. 192.5 μs)
```

But if I use `mwc-random ==0.15.*`,

```
cabal run -w ghc-8.8.3 LC --constraint='mwc-random ==0.15.*' -- --match prefix "nf/Scoped"
```

then the stats are... useless:

```
benchmarking nf/Scoped/
time                 10.01 ms   (-4.5517e13 s .. -4.5517e13 s)
                     0.999 R²   (-Infinity R² .. -Infinity R²)
mean                 9.960 ms   (9.960 ms .. 9.960 ms)
std dev              132.9 μs   (132.9 μs .. 132.9 μs)
```

---

The install plan diff contains *only* `mwc-random` change;
`random` is `1.2.0` in both, `statistics` are the same etc.

```diff
-mwc-random-0.14.0.0 lib
+mwc-random-0.15.0.0 lib

              ├─ mwc-random 0.14.0.0 -> 0.15.0.0
              │  ├─ math-functions-0.3.4.0 ┄┄
+++           │  ├─ random-1.2.0 ┄┄
              │  └─ time-1.9.3 ┄┄
```

---

https://hackage.haskell.org/package/mwc-random-0.15.0.0/changelog doesn't
mention anything which would tell me whether the issue is in `mwc-random`
itself or in how `criterion` uses it.

cc @Shimuuar

**Comment by phadej** [comment]
I can reproduce this with any benchmark suite I tried. 

https://github.com/phadej/dlist-nonempty is a small one dependency-wise (and otherwise).

Also GHC version doesn't seem to be relevant. Reproducible with GHC-8.10.1 and GHC-8.0.2.

**Comment by Shimuuar** [comment]
I strongly suspect it's mwc-randim's bug:
https://github.com/bos/mwc-random/issues/75 Random number generation for
Int/Word is completely broken in 0.15. I'm going to make bugfix release in
hour or two

**Comment by phadej** [comment]
I went ahead and deprecated `0.15.0.0` on Hackage, so it's not as easily picked up by cabal-install solver.

**Comment by Shimuuar** [comment]
Thanks for deprecation! I've uploaded 0.15.0.1 to hackage. I checked that criterion gives correct results with it

**Comment by phadej** [comment]
Works here as well. Thanks @Shimuuar!
