### ISSUE TITLE
Weird results benchmarking IO-free IO actions

### ISSUE THREAD

**Issue by Gabriella439** [bos/criterion#35]
I get strange results when benchmarking `IO` actions that don't do any actual `IO`.  This issue usually arises when benchmarking streaming libraries like `pipes` and `conduit` when I try to test the raw overhead of the streaming machinery.

To illustrate what I mean, consider these two pipelines for `pipes` and `conduit`:

``` haskell
pipes, conduit :: (Monad m) => Int -> m () 
pipes n = runEffect $ for (each [1..n] >-> P.map (+1) >-> P.filter even) discard
conduit n = C.sourceList [1..n] $= C.map (+1) $= C.filter even $$ C.sinkNull
```

These don't actually do any `IO`, so they type-check as any monad.  However, if I specialize them to the `IO` monad and benchmark them using `nfIO`, I get very different result from specializing them to the `Identity` monad and using `whnf`.

Here's the code I use to benchmark the two alternatives:

``` haskell
import Criterion.Main
import Data.Conduit
import qualified Data.Conduit.List as C
import Pipes
import qualified Pipes.Prelude as P

import Data.Functor.Identity

criterion :: Int -> IO ()
criterion n = defaultMain
    [ bgroup "IO"
        [ bench "pipes"   $ nfIO (pipes   n)
        , bench "conduit" $ nfIO (conduit n)
        ]
    , bgroup "Identity"
        [ bench "pipes"   $ whnf (runIdentity . pipes  ) n
        , bench "conduit" $ whnf (runIdentity . conduit) n
        ]
    ]

pipes, conduit :: (Monad m) => Int -> m ()
pipes n = runEffect $ for (each [1..n] >-> P.map (+1) >-> P.filter even) discard
conduit n = C.sourceList [1..n] $= C.map (+1) $= C.filter even $$ C.sinkNull

main = criterion (10^5)
```

... and here are the results.  I want to highlight that the benchmark results for specializing to `IO` are very different from specializing to `Identity`.  Usually the `IO`-based benchmarks are several orders of magnitude faster:

```
warming up
estimating clock resolution...
mean is 24.61508 ns (20480001 iterations)
found 390965 outliers among 20479999 samples (1.9%)
  265634 (1.3%) high mild
  125331 (0.6%) high severe
estimating cost of a clock call...
mean is 23.52013 ns (1 iterations)

benchmarking IO/pipes
mean: 71.52687 ns, lb 65.49627 ns, ub 91.83582 ns, ci 0.950
std dev: 50.86117 ns, lb 17.29679 ns, ub 113.8678 ns, ci 0.950
found 7 outliers among 100 samples (7.0%)
  4 (4.0%) high mild
  3 (3.0%) high severe
variance introduced by outliers: 98.970%
variance is severely inflated by outliers

benchmarking IO/conduit
mean: 1.327538 ms, lb 1.311253 ms, ub 1.353610 ms, ci 0.950
std dev: 103.8509 us, lb 73.29134 us, ub 144.2492 us, ci 0.950
found 11 outliers among 100 samples (11.0%)
  2 (2.0%) high mild
  9 (9.0%) high severe
variance introduced by outliers: 69.713%
variance is severely inflated by outliers

benchmarking Identity/pipes
mean: 3.579730 ms, lb 3.495507 ms, ub 3.642569 ms, ci 0.950
std dev: 371.3227 us, lb 294.6107 us, ub 451.7314 us, ci 0.950
found 35 outliers among 100 samples (35.0%)
  22 (22.0%) low severe
  6 (6.0%) high mild
  7 (7.0%) high severe
variance introduced by outliers: 80.047%
variance is severely inflated by outliers

benchmarking Identity/conduit
mean: 16.22628 ms, lb 16.17274 ms, ub 16.30177 ms, ci 0.950
std dev: 322.3388 us, lb 245.0389 us, ub 416.8648 us, ci 0.950
found 8 outliers among 100 samples (8.0%)
  7 (7.0%) high severe
variance introduced by outliers: 13.224%
variance is moderately inflated by outliers
```

Whenever I get a weird `criterion` result, I always compare to `time`.  In this case, I timed the above program by just changing the `main` function to either:

```
main = pipes (10^8)

-- or:

main = conduit (10^8)
```

This gave the following results:

```
$ time ./bench  # main = pipes (10^8)

real    0m2.405s
user    0m2.380s
sys 0m0.016s
...
$ time ./bench  # main = conduit (10^8)

real    0m16.243s
user    0m16.161s
sys 0m0.048s
```

If you scale these down 1000x to match the criterion tests they agree better with the `Identity`-based results.  Also, common sense says that there is no way that `pipes` is chewing through 10^6 elements in 71 nanoseconds on my laptop, which is the other reason I don't believe the `IO`-based benchmarks.

So I already have a work-around for this (specialize to `Identity` instead of `IO`), but I thought you might be interested because benchmarking `IO`-free `IO` actions seems to have triggered a weird corner case of `criterion` that could be worth investigating.  This issue occurs with both `criterion-0.8.0.0` and `criterion-0.9.0.0` and occurs with the `cfgPerformGC` flag set to either `True` or `False`.

I'm also pinging @cartazio on this because I mentioned this issue to him previously and he was interested in example code for this.

**Comment by Javran** [comment]
I come across this issue while trying to deal with some "pretend" IO issue. Just want to make a note that an alternative (that I end up using) is to just do an IO that executes the binary that does the computation as an external process, admittedly this is a sledgehammer solution but you can be sure nothing is shared between executions (and it does generalize to non-haskell programs if what we after is just the time elapsed).
