### ISSUE TITLE
Garbage collection not forced

### ISSUE THREAD

**Issue by jbransen** [bos/criterion#75]
It seems that garbage collection is not forced between runs. The --no-gc options does nothing, the internal name 'forceGC' only appears in the source 3 times: 

./Main/Options.hs:68:    , forceGC      = True
./Main.hs:117:-- >              forceGC = False
./Types.hs:90:    , forceGC      :: Bool

**Comment by bos** [comment]
Thank you for pointing out this omission.

**Comment by jbransen** [comment]
"we now unconditionally force garbage collection"

This still seems incorrect, as garbage collection is *not* forced. `performGC` is called only at the beginning of `runBenchmark`, but never in between benchmarks. I ran into problems because of this, adding a call to `performGC` before the call to `measure` in `runBenchmark` seems to have solved it, but I am not sure if that is the best location for forcing the GC.

**Comment by rrnewton** [comment]
@jbransen - `runBenchmark` does run a single benchmark.  

Do you mean that you would expect a call to `performGC` before each batch of iterations, i.e. each call to `measure`?  (I don't know if we have a standard name for those, I like "rounds" or "batches".)

This brings up some interesting questions.  Presumably major GC would happen after a deterministic number of iterations for a given benchmark.  This means as criterion scales the iterations, it would have a non-linear factor -- stair stepping when that threshold is crossed.

If we *don't* control GC between batches, then the effect may be more random.  But... I don't know if that is worse.  Randomization is the strategy used by [Stabilizer](https://people.cs.umass.edu/~emery/pubs/stabilizer-asplos13.pdf).

One thing we know for sure is that performing GC between every batch will slow things down overall and reduce the number of data points we get.

I'd like to test this alternative and look into it a bit further.  Clearly, the better thing would be to do [multivariate regression](https://blogs.janestreet.com/core_bench-micro-benchmarking-for-ocaml/) to get a better handle on the GC.

CC @craigcitro

**Comment by jbransen** [comment]
This issue is 1,5 years old, but yes, I believe what I meant is that I'd like to call `performGC` for each batch. IIRC, without forcing GC, there would be large deviations between the timings of my benchmarks, because occasionally the garbage collector kicked in.

**Comment by rrnewton** [comment]
I think we'll leave it at "in between-benchmarks" for now, because that's easy and the status quo, and revisit this again if we have more data.
