### ISSUE TITLE
Problems with `env` function

### ISSUE THREAD

**Issue by osa1** [bos/criterion#76]
I'm having these two problems with `env`:

1) All environments are created even when I pass a benchmark name to `defaultMain`. For example, in this program:

```haskell
module Main where

import Criterion
import Criterion.Main

main :: IO ()
main = defaultMain
  [ env setupEnv1 $ \ ~val -> bench "benchmark 1" (nf fibSlow 30)
  , env setupEnv2 $ \ ~val -> bench "benchmark 2" (nf fibFast 30)
  ]

setupEnv1 = putStrLn "creating environment 1"
setupEnv2 = putStrLn "creating environment 2"

fibSlow :: Int -> Int
fibSlow 0 = 0
fibSlow 1 = 1
fibSlow n = fibSlow (n-1) + fibSlow (n-2)

fibFast :: Int -> (Int, Int)
fibFast 0 = (1, 1)
fibFast 1 = (1, 2)
fibFast n
   | even n    = (a*a + b*b, c*c - a*a)
   | otherwise = (c*c - a*a, b*b + c*c)
 where
   (a,b) = fibFast (n `div` 2 - 1)
   c     = a + b
```

Even if specify which benchmarks to run, all the environments are created:

```
➜  criterion_bug  ./dist/dist-sandbox-38b4e6e6/build/criterion-bug/criterion-bug "benchmark 2"
creating environment 1
creating environment 2
benchmarking benchmark 2
time                 221.6 ns   (221.1 ns .. 222.2 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 221.9 ns   (221.4 ns .. 222.4 ns)
std dev              1.667 ns   (1.209 ns .. 2.599 ns)
```

Ideally this would create only the second environment.

```
➜  criterion_bug  ./dist/dist-sandbox-38b4e6e6/build/criterion-bug/criterion-bug "benchmark 1"
creating environment 1
benchmarking benchmark 1
time                 5.421 ms   (5.397 ms .. 5.448 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 5.471 ms   (5.452 ms .. 5.495 ms)
std dev              67.98 μs   (49.47 μs .. 85.05 μs)

creating environment 2
```

Similarly this would create only the first one.

2) Lazy pattern matching as described in the `env` documentation:

> Lazy pattern matching. In situations where a "real" environment is not needed, e.g. if a list of benchmark names is being generated, undefined will be passed to the function that receives the environment. This avoids the overhead of generating an environment that will not actually be used.
>
> The function that receives the environment must use lazy pattern matching to deconstruct the tuple, as use of strict pattern matching will cause a crash if undefined is passed in.

seems wrong. For example, if I change my program to create environments like this:

```haskell
setupEnv1, setupEnv2 :: IO (Int, Int)
setupEnv1 = putStrLn "creating environment 1" >> return (undefined, undefined)
setupEnv2 = putStrLn "creating environment 2" >> return (undefined, undefined)
```

It fails like this:

```
➜  criterion_bug  ./dist/dist-sandbox-38b4e6e6/build/criterion-bug/criterion-bug "benchmark 1"
creating environment 1
criterion-bug: Prelude.undefined
```

Note that I have lazy pattern matching here(see the full code listing above).

Any ideas?

**Comment by bos** [comment]
Thanks!
