### ISSUE TITLE
`env` like function for freeing resources

### ISSUE THREAD

**Issue by osa1** [bos/criterion#79]
I have some number of benchmarks and in each one of them, I'm allocating some resources from a limited pool of resources. I need to free the resources after each benchmark, because rest of the benchmarks will be using those resources, however, I don't want to measure time spend on freeing the resources. As far as I can see Criterion doesn't have a way to do this right now. Implementing this would be really awesome.

**Comment by mgsloan** [comment]
+1

I just needed this as well.

**Comment by mgsloan** [comment]
It would also be nice to have a variant which doesn't require an `NFData` instance for the environment, as it could be the responsibility of the environment initialization code to do such evaluation.

**Comment by osa1** [comment]
> It would also be nice to have a variant which doesn't require an NFData instance for the environment, as it could be the responsibility of the environment initialization code to do such evaluation.

Can't you just wrap your data with a newtype, and implement `instance NFData YourData where rnf (YourData _) = ()` ?

**Comment by mgsloan** [comment]
True!  Maybe the `NFData` constraint isn't so bad to let the user know they should consider this.
