### ISSUE TITLE
Consider including the current git commit at compile time in reports

### ISSUE THREAD

**Issue by jberryman** [bos/criterion#86]
This may be out of scope for the project and a bit out of left field, bit a feature request: at compile time, if we're in a git repo, get the latest commit hash and whether HEAD is clean and include that information in any reports generated.

In my own lame workflow I often have a bunch of old html reports lying around that I use to periodically do regression checks as I develop. Sometimes I don't keep very good track of when they were created.

**Comment by rrnewton** [comment]
We do this postfacto when we use a combination of criterion and hsbencher.  (We have a command called `hsbencher-fusion-upload-criterion` that adds the extra metadata.)

Unfortunately criterion itself is very much not in the business of machine examination / metadata gathering.  I think it would be a big shift for it to grow in that direction, and maybe we should emphasize integration with other tools like hsbencher.
