### ISSUE TITLE
ASCII output in console

### ISSUE THREAD

**Issue by kc1212** [bos/criterion#91]
Hi, is there an option to output the results in plain ASCII in the console? Currently there are symbols such as "μs", if I copy it to a program that only supports ASCII then things can go wrong. I had a look at --help but didn't see any relevant optons.

I can probably send the PR when I have more time, if the option isn't there.

**Comment by ivanperez-keera** [comment]
Unless it causes problems with terminals that do not support certain encodings, I think criterion should not deal with this at all. You can always pipe the output to `sed` and apply whatever substitution you want:
``` bash
$ ./.cabal-sandbox/bin/iorefcriterion | sed -e 's/μ/u/g'
benchmarking main/IORefs/Run up to
time                 63.41 us   (63.39 us .. 63.43 us)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 63.45 us   (63.44 us .. 63.46 us)
std dev              26.92 ns   (18.84 ns .. 39.11 ns)
```

Read `sed`'s manual to find out how to list all the commands in one file and avoid very long argument lists.

**Comment by kc1212** [comment]
That's a fair point, I can live with that.
