### ISSUE TITLE
Replace the `undefined` that `env` uses with a more descriptive error

### ISSUE THREAD

**Issue by Gabriel439** [bos/criterion#96]
`env` passed in an `undefined` value when generating the list of benchmark names.  This is just a request to replace the `undefined` with a more descriptive error message like:

```haskell
error "Criterion.env could not determine the list of your benchmarks since they force the environment.  See the documentation of `Criterion.env` for more details"
```

It doesn't have to be exactly that error, but just something more helpful than `"Prelude.undefined"`

**Comment by bos** [comment]
Thanks!

**Comment by Gabriel439** [comment]
You're welcome!
